import pygame
from class_Juego import Juego
#===FEDERICO BARONE 1A===
#===INSTRUCCIONES DE JUEGO===
#P = PAUSAR JUEGO
#R = REINICIAR NIVEL
#N = SELECCIONAR NIVEL
#FECHA SUPERIOR = SALTO DEL PERSONAJE
#FLECHA IZQUIERDA Y DERECHA = MOVIMIENTO HORIZONTAL PERSONAJE
#ESPACIO = DISPARAR BOLAS FUEGO

juego = Juego()

juego.mostrar_pantalla_inicio() 
